name: Merge con develop al encontrar "funcionalidad terminada"

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed

jobs:
  detect-and-merge:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    #if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Revisar commit en todas las ramas
        id: find_branch
        run: |
          for branch in $(git branch -r | grep -v '\->'); do
            branch_name=$(echo $branch | sed 's#origin/##')  
            git checkout $branch_name
            if git log -1 --pretty=format:"%s" | grep -q "Funcionalidad terminada"; then
              echo "::set-output name=source-branch::$branch_name"
              break
            fi
          done

      - name: Merge the branch if a matching commit was found
        if: steps.find_branch.outputs.source-branch != ''
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target-branch: develop
          source-branch: ${{ steps.find_branch.outputs.source-branch }}
