name: Release Workflow

on:
  push:
    branches:
      - develop
  workflow_run:
    workflows: ['Merge con develop']
    types:
      - completed
      
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create release branch
        id: create_release_branch
        run: |
          git checkout develop
          release_branch="release"
          git checkout develop
          git checkout -b $release_branch
          git push origin $release_branch
          echo "::set-output name=release-branch::$release_branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  run-tests:
    runs-on: ubuntu-latest
    needs: create-release-branch

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.14'

      - name: Install requirements
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest

  merge-to-main:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
  
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
  
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches
  
      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
  
      - name: Fetch all branches
        run: git fetch --all
  
      - name: Check branches status
        run: |
          git checkout release
          git log --oneline -n 5
          git checkout main
          git log --oneline -n 5
  
      - name: Merge release branch into main
        run: |
          git checkout main
          git merge --no-ff release
          git push origin main
          git push origin --delete release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

