name: Release Workflow

on:
  push:
    branches:
      - develop

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
    
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0


      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create release branch
        id: create_release_branch
        run: |
          release_branch="release-$(date +'%Y%m%d%H%M%S')"
          git checkout -b $release_branch
          git push origin $release_branch
          echo "::set-output name=release-branch::$release_branch"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  run-tests:
    runs-on: ubuntu-latest
    needs: create-release-branch

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.14'

      - name: Install requirements
        run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest

  merge-to-main:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()
  
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches
  
      - name: Set up Git user
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
  
      - name: Fetch all branches
        run: git fetch origin
  
      - name: Checkout the main branch
        run: git checkout main
  
      - name: Merge release branch into main
        run: |
          git merge --no-ff ${{ needs.create-release-branch.outputs.release-branch }}
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  delete-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    needs: merge-to-main
    if: success()

    steps:
      - name: Delete the release branch
        run: |
          git push origin --delete ${{ needs.create-release-branch.outputs.release-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
