name: Merge con develop

on:
  push:
    branches:
      - '**'

jobs:
  # Job 1: Ejecuta los tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.14' # Use the correct Python version


      - name: Run tests
        run: python -m unittest

  # Job 2: Detecta ramas con commit de funcionalidad terminada y hace merge
  detect-and-merge:
    runs-on: ubuntu-latest

    # Only run this job if the 'test' job completes successfully
    needs: test

    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Revisar commit en todas las ramas
        id: find_branch
        run: |
          for branch in $(git branch -r | grep -v '\->'); do
            branch_name=$(echo $branch | sed 's#origin/##')  
            git checkout $branch_name
            if git log -1 --pretty=format:"%s" | grep -q "Funcionalidad terminada"; then
              echo "::set-output name=source-branch::$branch_name"
              break
            fi
          done

      - name: Merge the branch if a matching commit was found
        if: steps.find_branch.outputs.source-branch != ''
        uses: tukasz/direct-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          target-branch: develop
          source-branch: ${{ steps.find_branch.outputs.source-branch }}
