name: Python Tests

# Controls when the action will run
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

# Define the jobs to be run
jobs:
  test:

    # Runs on the latest available version of Ubuntu
    runs-on: ubuntu-latest

    # Steps to be performed
    steps:
    # Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.14' # Replace with your required Python version

    # Install dependencies
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install pytest unittest

    # Run pytest
    - name: Run tests
      run: |
        python -m unittest
